version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/opt'
    environment:
      - DB_USER=root
      - DB_NAME=app
      - DB_PASSWORD=password
      - DB_HOST=db
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    command: bash -c "
      rake db:create
      && rails s -b 0.0.0.0"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=app
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${password}"
    ports:
      - "3306:3306"
